# Exceções específicas
class AuthError(Exception): ...


class InvalidCredentials(AuthError): ...


class RefreshNotFound(AuthError): ...


class RefreshReuseDetected(AuthError): ...


class RefreshExpired(AuthError): ...


class RefreshInvalid(AuthError): ...
